export interface CollegeEntry {
  id: string;
  name: string;
  location: string;
  state: string;
  city: string;
  type: "Community College" | "Public University" | "Private University" | "Technical College";
  tuitionInState: number;
  tuitionOutState: number;
  tuition: string;
  acceptanceRate: string;
  acceptanceRateNum: number;
  minGPA: number;
  avgGPA: number;
  ranking: number;
  enrollmentSize: number;
  majors: string[];
  tags: string[];
  satRange: string;
  actRange: string;
  financialAidPercent: number;
  avgAidAmount: number;
  graduationRate: number;
  description: string;
  website: string;
  region: string;
}

export const collegeDatabase: CollegeEntry[] = [
  // ============ CALIFORNIA ============
  {
    id: "ucla",
    name: "University of California, Los Angeles",
    location: "Los Angeles, CA",
    state: "CA",
    city: "Los Angeles",
    type: "Public University",
    tuitionInState: 13804,
    tuitionOutState: 43022,
    tuition: "$13,804 (in-state) / $43,022 (out-of-state)",
    acceptanceRate: "9%",
    acceptanceRateNum: 0.09,
    minGPA: 3.5,
    avgGPA: 3.9,
    ranking: 15,
    enrollmentSize: 46000,
    majors: ["Computer Science", "Engineering", "Biology", "Psychology", "Business Economics", "Political Science", "Film & Television", "Mathematics"],
    tags: ["research", "diverse", "urban", "athletics", "stem", "arts"],
    satRange: "1290-1510",
    actRange: "29-34",
    financialAidPercent: 58,
    avgAidAmount: 21000,
    graduationRate: 92,
    description: "A top public research university known for academic excellence and vibrant campus life in the heart of LA.",
    website: "https://www.ucla.edu",
    region: "West"
  },
  {
    id: "stanford",
    name: "Stanford University",
    location: "Stanford, CA",
    state: "CA",
    city: "Stanford",
    type: "Private University",
    tuitionInState: 59394,
    tuitionOutState: 59394,
    tuition: "$59,394",
    acceptanceRate: "4%",
    acceptanceRateNum: 0.04,
    minGPA: 3.8,
    avgGPA: 3.96,
    ranking: 3,
    enrollmentSize: 17000,
    majors: ["Computer Science", "Engineering", "Human Biology", "Economics", "Management Science", "International Relations", "Psychology"],
    tags: ["research", "silicon-valley", "entrepreneurship", "stem", "elite", "innovation"],
    satRange: "1500-1570",
    actRange: "34-36",
    financialAidPercent: 68,
    avgAidAmount: 56000,
    graduationRate: 96,
    description: "A world-renowned private research university and the heart of Silicon Valley innovation.",
    website: "https://www.stanford.edu",
    region: "West"
  },
  {
    id: "smc",
    name: "Santa Monica College",
    location: "Santa Monica, CA",
    state: "CA",
    city: "Santa Monica",
    type: "Community College",
    tuitionInState: 1380,
    tuitionOutState: 8820,
    tuition: "$1,380 (in-state) / $8,820 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.5,
    ranking: 1,
    enrollmentSize: 30000,
    majors: ["Business", "Nursing", "Computer Science", "Liberal Arts", "Film Production", "Graphic Design", "Accounting", "Early Childhood Education"],
    tags: ["community", "transfer", "affordable", "open-enrollment", "flexible", "beach"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 72,
    avgAidAmount: 5200,
    graduationRate: 40,
    description: "The #1 transfer college to UCLA and the UC system with excellent programs and beautiful beachside location.",
    website: "https://www.smc.edu",
    region: "West"
  },
  {
    id: "ucb",
    name: "University of California, Berkeley",
    location: "Berkeley, CA",
    state: "CA",
    city: "Berkeley",
    type: "Public University",
    tuitionInState: 14312,
    tuitionOutState: 44066,
    tuition: "$14,312 (in-state) / $44,066 (out-of-state)",
    acceptanceRate: "11%",
    acceptanceRateNum: 0.11,
    minGPA: 3.5,
    avgGPA: 3.89,
    ranking: 4,
    enrollmentSize: 45000,
    majors: ["Computer Science", "Electrical Engineering", "Business", "Economics", "Data Science", "Political Science", "Chemistry", "Molecular Biology"],
    tags: ["research", "stem", "diverse", "urban", "entrepreneurship", "innovation"],
    satRange: "1310-1530",
    actRange: "30-35",
    financialAidPercent: 56,
    avgAidAmount: 22000,
    graduationRate: 93,
    description: "One of the world's leading public research universities, known for STEM and social activism.",
    website: "https://www.berkeley.edu",
    region: "West"
  },
  {
    id: "ccsf",
    name: "City College of San Francisco",
    location: "San Francisco, CA",
    state: "CA",
    city: "San Francisco",
    type: "Community College",
    tuitionInState: 1104,
    tuitionOutState: 7500,
    tuition: "$1,104 (in-state) / $7,500 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.3,
    ranking: 8,
    enrollmentSize: 28000,
    majors: ["Nursing", "Computer Networking", "Culinary Arts", "Business", "Liberal Arts", "Biotechnology", "Early Childhood Education"],
    tags: ["community", "transfer", "affordable", "open-enrollment", "urban", "diverse"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 78,
    avgAidAmount: 4800,
    graduationRate: 35,
    description: "A free community college in San Francisco offering 50+ programs and strong transfer pathways.",
    website: "https://www.ccsf.edu",
    region: "West"
  },
  {
    id: "sdsu",
    name: "San Diego State University",
    location: "San Diego, CA",
    state: "CA",
    city: "San Diego",
    type: "Public University",
    tuitionInState: 8088,
    tuitionOutState: 19548,
    tuition: "$8,088 (in-state) / $19,548 (out-of-state)",
    acceptanceRate: "38%",
    acceptanceRateNum: 0.38,
    minGPA: 2.8,
    avgGPA: 3.6,
    ranking: 105,
    enrollmentSize: 36000,
    majors: ["Business", "Psychology", "Criminal Justice", "Biology", "Nursing", "Engineering", "Public Health", "Kinesiology"],
    tags: ["mid-range", "diverse", "athletics", "research", "warm-climate"],
    satRange: "1120-1310",
    actRange: "23-29",
    financialAidPercent: 62,
    avgAidAmount: 11000,
    graduationRate: 77,
    description: "A leading public research university with strong programs and excellent campus life in sunny San Diego.",
    website: "https://www.sdsu.edu",
    region: "West"
  },
  // ============ TEXAS ============
  {
    id: "ut-austin",
    name: "University of Texas at Austin",
    location: "Austin, TX",
    state: "TX",
    city: "Austin",
    type: "Public University",
    tuitionInState: 11448,
    tuitionOutState: 41070,
    tuition: "$11,448 (in-state) / $41,070 (out-of-state)",
    acceptanceRate: "31%",
    acceptanceRateNum: 0.31,
    minGPA: 3.2,
    avgGPA: 3.8,
    ranking: 32,
    enrollmentSize: 51000,
    majors: ["Computer Science", "Business", "Engineering", "Communications", "Biology", "Economics", "Government", "Nursing"],
    tags: ["research", "stem", "athletics", "tech-hub", "large", "diverse"],
    satRange: "1230-1480",
    actRange: "27-33",
    financialAidPercent: 50,
    avgAidAmount: 13000,
    graduationRate: 87,
    description: "Flagship Texas public university with world-class engineering and business programs in vibrant Austin.",
    website: "https://www.utexas.edu",
    region: "South"
  },
  {
    id: "tamu",
    name: "Texas A&M University",
    location: "College Station, TX",
    state: "TX",
    city: "College Station",
    type: "Public University",
    tuitionInState: 12413,
    tuitionOutState: 39240,
    tuition: "$12,413 (in-state) / $39,240 (out-of-state)",
    acceptanceRate: "63%",
    acceptanceRateNum: 0.63,
    minGPA: 2.5,
    avgGPA: 3.6,
    ranking: 47,
    enrollmentSize: 72000,
    majors: ["Engineering", "Agriculture", "Business", "Veterinary Science", "Biology", "Computer Science", "Political Science"],
    tags: ["research", "stem", "athletics", "rural", "large", "military-friendly"],
    satRange: "1130-1370",
    actRange: "25-31",
    financialAidPercent: 55,
    avgAidAmount: 11500,
    graduationRate: 82,
    description: "One of the largest universities in the US with top engineering and agriculture programs.",
    website: "https://www.tamu.edu",
    region: "South"
  },
  {
    id: "hcc",
    name: "Houston Community College",
    location: "Houston, TX",
    state: "TX",
    city: "Houston",
    type: "Community College",
    tuitionInState: 1680,
    tuitionOutState: 3360,
    tuition: "$1,680 (in-state) / $3,360 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.4,
    ranking: 3,
    enrollmentSize: 55000,
    majors: ["Nursing", "Business", "Information Technology", "Welding", "Automotive", "Liberal Arts", "Culinary", "Dental Hygiene"],
    tags: ["community", "affordable", "open-enrollment", "diverse", "vocational", "urban"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 70,
    avgAidAmount: 4500,
    graduationRate: 22,
    description: "One of the largest community college systems in the US serving the diverse Houston metro area.",
    website: "https://www.hccs.edu",
    region: "South"
  },
  {
    id: "dcc",
    name: "Dallas College",
    location: "Dallas, TX",
    state: "TX",
    city: "Dallas",
    type: "Community College",
    tuitionInState: 1770,
    tuitionOutState: 3330,
    tuition: "$1,770 (in-state) / $3,330 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.3,
    ranking: 5,
    enrollmentSize: 80000,
    majors: ["Business", "Computer Science", "Nursing", "Engineering Technology", "Liberal Arts", "Criminal Justice", "Cybersecurity"],
    tags: ["community", "affordable", "open-enrollment", "large", "urban", "diverse"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 65,
    avgAidAmount: 4200,
    graduationRate: 25,
    description: "The largest community college system in Texas with 7 campuses across the Dallas area.",
    website: "https://www.dallascollege.edu",
    region: "South"
  },
  // ============ NEW YORK ============
  {
    id: "columbia",
    name: "Columbia University",
    location: "New York, NY",
    state: "NY",
    city: "New York",
    type: "Private University",
    tuitionInState: 65524,
    tuitionOutState: 65524,
    tuition: "$65,524",
    acceptanceRate: "4%",
    acceptanceRateNum: 0.04,
    minGPA: 3.8,
    avgGPA: 3.95,
    ranking: 12,
    enrollmentSize: 33000,
    majors: ["Political Science", "Computer Science", "Economics", "Engineering", "English", "History", "Neuroscience", "Film Studies"],
    tags: ["ivy-league", "research", "elite", "urban", "diverse", "arts"],
    satRange: "1500-1560",
    actRange: "34-35",
    financialAidPercent: 55,
    avgAidAmount: 62000,
    graduationRate: 95,
    description: "An Ivy League university in the heart of Manhattan with world-class academics across all fields.",
    website: "https://www.columbia.edu",
    region: "Northeast"
  },
  {
    id: "nyu",
    name: "New York University",
    location: "New York, NY",
    state: "NY",
    city: "New York",
    type: "Private University",
    tuitionInState: 58168,
    tuitionOutState: 58168,
    tuition: "$58,168",
    acceptanceRate: "12%",
    acceptanceRateNum: 0.12,
    minGPA: 3.5,
    avgGPA: 3.7,
    ranking: 35,
    enrollmentSize: 52000,
    majors: ["Business", "Film & Television", "Economics", "Computer Science", "Nursing", "Liberal Arts", "Drama", "Data Science"],
    tags: ["urban", "diverse", "arts", "business", "global", "research"],
    satRange: "1370-1530",
    actRange: "31-35",
    financialAidPercent: 48,
    avgAidAmount: 38000,
    graduationRate: 86,
    description: "A major private research university in downtown Manhattan known for business, arts, and global programs.",
    website: "https://www.nyu.edu",
    region: "Northeast"
  },
  {
    id: "suny-stony",
    name: "Stony Brook University (SUNY)",
    location: "Stony Brook, NY",
    state: "NY",
    city: "Stony Brook",
    type: "Public University",
    tuitionInState: 10556,
    tuitionOutState: 28516,
    tuition: "$10,556 (in-state) / $28,516 (out-of-state)",
    acceptanceRate: "49%",
    acceptanceRateNum: 0.49,
    minGPA: 2.8,
    avgGPA: 3.5,
    ranking: 58,
    enrollmentSize: 26000,
    majors: ["Biology", "Computer Science", "Health Science", "Psychology", "Engineering", "Business", "Nursing", "Mathematics"],
    tags: ["research", "stem", "affordable", "suburban", "diverse"],
    satRange: "1270-1450",
    actRange: "28-33",
    financialAidPercent: 60,
    avgAidAmount: 14000,
    graduationRate: 76,
    description: "A leading SUNY research university known for STEM programs and healthcare education.",
    website: "https://www.stonybrook.edu",
    region: "Northeast"
  },
  {
    id: "bmcc",
    name: "Borough of Manhattan Community College (CUNY)",
    location: "New York, NY",
    state: "NY",
    city: "New York",
    type: "Community College",
    tuitionInState: 5280,
    tuitionOutState: 8340,
    tuition: "$5,280 (in-state) / $8,340 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.2,
    ranking: 6,
    enrollmentSize: 27000,
    majors: ["Business", "Nursing", "Liberal Arts", "Computer Science", "Accounting", "Criminal Justice", "Media Arts"],
    tags: ["community", "affordable", "open-enrollment", "urban", "diverse", "transfer"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 82,
    avgAidAmount: 6000,
    graduationRate: 22,
    description: "One of NYC's largest community colleges with strong transfer programs to CUNY 4-year schools.",
    website: "https://www.bmcc.cuny.edu",
    region: "Northeast"
  },
  // ============ FLORIDA ============
  {
    id: "uf",
    name: "University of Florida",
    location: "Gainesville, FL",
    state: "FL",
    city: "Gainesville",
    type: "Public University",
    tuitionInState: 6380,
    tuitionOutState: 28658,
    tuition: "$6,380 (in-state) / $28,658 (out-of-state)",
    acceptanceRate: "23%",
    acceptanceRateNum: 0.23,
    minGPA: 3.3,
    avgGPA: 4.4,
    ranking: 28,
    enrollmentSize: 56000,
    majors: ["Business", "Engineering", "Biology", "Computer Science", "Psychology", "Finance", "Health Science", "Journalism"],
    tags: ["research", "large", "athletics", "stem", "affordable"],
    satRange: "1300-1470",
    actRange: "29-33",
    financialAidPercent: 55,
    avgAidAmount: 12000,
    graduationRate: 90,
    description: "Top-ranked public university with affordable tuition and strong programs across all fields.",
    website: "https://www.ufl.edu",
    region: "South"
  },
  {
    id: "fsu",
    name: "Florida State University",
    location: "Tallahassee, FL",
    state: "FL",
    city: "Tallahassee",
    type: "Public University",
    tuitionInState: 6517,
    tuitionOutState: 21683,
    tuition: "$6,517 (in-state) / $21,683 (out-of-state)",
    acceptanceRate: "25%",
    acceptanceRateNum: 0.25,
    minGPA: 3.0,
    avgGPA: 4.1,
    ranking: 53,
    enrollmentSize: 45000,
    majors: ["Business", "Psychology", "Biology", "Criminal Justice", "Engineering", "Film", "Music", "Social Work"],
    tags: ["research", "athletics", "arts", "mid-range", "diverse"],
    satRange: "1200-1360",
    actRange: "26-31",
    financialAidPercent: 58,
    avgAidAmount: 10500,
    graduationRate: 83,
    description: "A major research university known for strong academics, athletics, and creative arts.",
    website: "https://www.fsu.edu",
    region: "South"
  },
  {
    id: "mdc",
    name: "Miami Dade College",
    location: "Miami, FL",
    state: "FL",
    city: "Miami",
    type: "Community College",
    tuitionInState: 3430,
    tuitionOutState: 11880,
    tuition: "$3,430 (in-state) / $11,880 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.3,
    ranking: 2,
    enrollmentSize: 60000,
    majors: ["Nursing", "Business", "Engineering Technology", "Film", "Liberal Arts", "Cybersecurity", "Education"],
    tags: ["community", "affordable", "open-enrollment", "diverse", "large", "urban"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 76,
    avgAidAmount: 5000,
    graduationRate: 30,
    description: "The largest college in the US by enrollment with 8 campuses across Miami-Dade County.",
    website: "https://www.mdc.edu",
    region: "South"
  },
  // ============ ILLINOIS ============
  {
    id: "uiuc",
    name: "University of Illinois Urbana-Champaign",
    location: "Champaign, IL",
    state: "IL",
    city: "Champaign",
    type: "Public University",
    tuitionInState: 16862,
    tuitionOutState: 36068,
    tuition: "$16,862 (in-state) / $36,068 (out-of-state)",
    acceptanceRate: "45%",
    acceptanceRateNum: 0.45,
    minGPA: 2.8,
    avgGPA: 3.7,
    ranking: 35,
    enrollmentSize: 56000,
    majors: ["Computer Science", "Engineering", "Business", "Biology", "Psychology", "Accounting", "Crop Science"],
    tags: ["research", "stem", "large", "athletics", "engineering-top"],
    satRange: "1270-1480",
    actRange: "28-34",
    financialAidPercent: 52,
    avgAidAmount: 16000,
    graduationRate: 86,
    description: "One of the top engineering and computer science schools globally with strong research output.",
    website: "https://www.illinois.edu",
    region: "Midwest"
  },
  {
    id: "ccc",
    name: "City Colleges of Chicago",
    location: "Chicago, IL",
    state: "IL",
    city: "Chicago",
    type: "Community College",
    tuitionInState: 3600,
    tuitionOutState: 9500,
    tuition: "$3,600 (in-state) / $9,500 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.2,
    ranking: 7,
    enrollmentSize: 70000,
    majors: ["Nursing", "Business", "Information Technology", "Liberal Arts", "Manufacturing", "Construction", "Culinary"],
    tags: ["community", "affordable", "open-enrollment", "urban", "vocational", "diverse"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 80,
    avgAidAmount: 5500,
    graduationRate: 18,
    description: "Seven community colleges across Chicago offering free tuition for qualifying residents.",
    website: "https://www.ccc.edu",
    region: "Midwest"
  },
  // ============ GEORGIA ============
  {
    id: "gatech",
    name: "Georgia Institute of Technology",
    location: "Atlanta, GA",
    state: "GA",
    city: "Atlanta",
    type: "Public University",
    tuitionInState: 12852,
    tuitionOutState: 33794,
    tuition: "$12,852 (in-state) / $33,794 (out-of-state)",
    acceptanceRate: "17%",
    acceptanceRateNum: 0.17,
    minGPA: 3.3,
    avgGPA: 3.97,
    ranking: 33,
    enrollmentSize: 44000,
    majors: ["Computer Science", "Mechanical Engineering", "Electrical Engineering", "Industrial Engineering", "Business", "Biomedical Engineering"],
    tags: ["research", "stem", "engineering-top", "tech-hub", "urban"],
    satRange: "1370-1530",
    actRange: "31-35",
    financialAidPercent: 48,
    avgAidAmount: 15000,
    graduationRate: 90,
    description: "A top-ranked STEM university consistently rated among the best engineering schools in the world.",
    website: "https://www.gatech.edu",
    region: "South"
  },
  {
    id: "spelman",
    name: "Spelman College",
    location: "Atlanta, GA",
    state: "GA",
    city: "Atlanta",
    type: "Private University",
    tuitionInState: 30814,
    tuitionOutState: 30814,
    tuition: "$30,814",
    acceptanceRate: "35%",
    acceptanceRateNum: 0.35,
    minGPA: 3.0,
    avgGPA: 3.7,
    ranking: 56,
    enrollmentSize: 2300,
    majors: ["Biology", "Psychology", "Political Science", "English", "Computer Science", "Mathematics", "Economics"],
    tags: ["women-only", "liberal-arts", "diverse", "small", "community"],
    satRange: "1100-1280",
    actRange: "23-28",
    financialAidPercent: 90,
    avgAidAmount: 18000,
    graduationRate: 76,
    description: "A top-ranked women's college known for producing leaders in STEM, business, and public service.",
    website: "https://www.spelman.edu",
    region: "South"
  },
  {
    id: "morehouse",
    name: "Morehouse College",
    location: "Atlanta, GA",
    state: "GA",
    city: "Atlanta",
    type: "Private University",
    tuitionInState: 29468,
    tuitionOutState: 29468,
    tuition: "$29,468",
    acceptanceRate: "40%",
    acceptanceRateNum: 0.40,
    minGPA: 2.8,
    avgGPA: 3.5,
    ranking: 60,
    enrollmentSize: 2200,
    majors: ["Business", "Biology", "Computer Science", "Political Science", "Psychology", "Cinema & Media", "Music"],
    tags: ["men-only", "liberal-arts", "diverse", "small", "leadership"],
    satRange: "1060-1240",
    actRange: "21-27",
    financialAidPercent: 92,
    avgAidAmount: 17000,
    graduationRate: 68,
    description: "A prestigious men's college that has produced leaders like Martin Luther King Jr. and Spike Lee.",
    website: "https://www.morehouse.edu",
    region: "South"
  },
  // ============ NORTH CAROLINA ============
  {
    id: "unc",
    name: "University of North Carolina at Chapel Hill",
    location: "Chapel Hill, NC",
    state: "NC",
    city: "Chapel Hill",
    type: "Public University",
    tuitionInState: 8998,
    tuitionOutState: 37558,
    tuition: "$8,998 (in-state) / $37,558 (out-of-state)",
    acceptanceRate: "17%",
    acceptanceRateNum: 0.17,
    minGPA: 3.3,
    avgGPA: 4.5,
    ranking: 22,
    enrollmentSize: 31000,
    majors: ["Biology", "Business", "Computer Science", "Psychology", "Political Science", "Economics", "Nursing", "Journalism"],
    tags: ["research", "athletics", "affordable", "diverse", "suburban"],
    satRange: "1310-1490",
    actRange: "29-34",
    financialAidPercent: 55,
    avgAidAmount: 18000,
    graduationRate: 91,
    description: "One of the oldest and most prestigious public universities known for research and Carolina spirit.",
    website: "https://www.unc.edu",
    region: "South"
  },
  // ============ MASSACHUSETTS ============
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, MA",
    state: "MA",
    city: "Cambridge",
    type: "Private University",
    tuitionInState: 59750,
    tuitionOutState: 59750,
    tuition: "$59,750",
    acceptanceRate: "4%",
    acceptanceRateNum: 0.04,
    minGPA: 3.8,
    avgGPA: 3.97,
    ranking: 2,
    enrollmentSize: 11500,
    majors: ["Computer Science", "Engineering", "Mathematics", "Physics", "Biology", "Economics", "Architecture", "Artificial Intelligence"],
    tags: ["elite", "research", "stem", "innovation", "technology", "small"],
    satRange: "1510-1580",
    actRange: "35-36",
    financialAidPercent: 58,
    avgAidAmount: 54000,
    graduationRate: 95,
    description: "The world's leading institute of technology and innovation known for groundbreaking research.",
    website: "https://www.mit.edu",
    region: "Northeast"
  },
  {
    id: "umass",
    name: "University of Massachusetts Amherst",
    location: "Amherst, MA",
    state: "MA",
    city: "Amherst",
    type: "Public University",
    tuitionInState: 16952,
    tuitionOutState: 38700,
    tuition: "$16,952 (in-state) / $38,700 (out-of-state)",
    acceptanceRate: "64%",
    acceptanceRateNum: 0.64,
    minGPA: 2.5,
    avgGPA: 3.5,
    ranking: 67,
    enrollmentSize: 32000,
    majors: ["Computer Science", "Business", "Biology", "Psychology", "Engineering", "Nursing", "Hospitality", "Kinesiology"],
    tags: ["research", "affordable", "rural", "diverse", "large", "stem"],
    satRange: "1200-1380",
    actRange: "27-32",
    financialAidPercent: 60,
    avgAidAmount: 16000,
    graduationRate: 80,
    description: "Flagship of the UMass system with strong CS and business programs in scenic Western Massachusetts.",
    website: "https://www.umass.edu",
    region: "Northeast"
  },
  {
    id: "bunker-hill",
    name: "Bunker Hill Community College",
    location: "Boston, MA",
    state: "MA",
    city: "Boston",
    type: "Community College",
    tuitionInState: 4320,
    tuitionOutState: 10200,
    tuition: "$4,320 (in-state) / $10,200 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.2,
    ranking: 9,
    enrollmentSize: 15000,
    majors: ["Nursing", "Criminal Justice", "Business", "Liberal Arts", "Computer Science", "Culinary Arts", "Early Childhood Education"],
    tags: ["community", "affordable", "open-enrollment", "urban", "diverse", "transfer"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 75,
    avgAidAmount: 5500,
    graduationRate: 15,
    description: "Boston's largest community college with strong health care and STEM transfer programs.",
    website: "https://www.bhcc.edu",
    region: "Northeast"
  },
  // ============ MICHIGAN ============
  {
    id: "umich",
    name: "University of Michigan",
    location: "Ann Arbor, MI",
    state: "MI",
    city: "Ann Arbor",
    type: "Public University",
    tuitionInState: 16736,
    tuitionOutState: 55584,
    tuition: "$16,736 (in-state) / $55,584 (out-of-state)",
    acceptanceRate: "18%",
    acceptanceRateNum: 0.18,
    minGPA: 3.3,
    avgGPA: 3.9,
    ranking: 21,
    enrollmentSize: 48000,
    majors: ["Computer Science", "Business", "Engineering", "Psychology", "Economics", "Political Science", "Biology", "Nursing"],
    tags: ["research", "athletics", "large", "diverse", "stem", "prestigious"],
    satRange: "1340-1530",
    actRange: "31-34",
    financialAidPercent: 52,
    avgAidAmount: 22000,
    graduationRate: 93,
    description: "One of the most prestigious public universities in the US with top programs across all disciplines.",
    website: "https://umich.edu",
    region: "Midwest"
  },
  // ============ OHIO ============
  {
    id: "osu",
    name: "The Ohio State University",
    location: "Columbus, OH",
    state: "OH",
    city: "Columbus",
    type: "Public University",
    tuitionInState: 11936,
    tuitionOutState: 35019,
    tuition: "$11,936 (in-state) / $35,019 (out-of-state)",
    acceptanceRate: "53%",
    acceptanceRateNum: 0.53,
    minGPA: 2.5,
    avgGPA: 3.7,
    ranking: 43,
    enrollmentSize: 61000,
    majors: ["Business", "Engineering", "Psychology", "Biology", "Computer Science", "Nursing", "Communication", "Finance"],
    tags: ["research", "athletics", "large", "diverse", "mid-range", "urban"],
    satRange: "1210-1410",
    actRange: "27-32",
    financialAidPercent: 58,
    avgAidAmount: 13000,
    graduationRate: 83,
    description: "One of the largest universities in the US with strong athletics and comprehensive academic programs.",
    website: "https://www.osu.edu",
    region: "Midwest"
  },
  // ============ PENNSYLVANIA ============
  {
    id: "upenn",
    name: "University of Pennsylvania",
    location: "Philadelphia, PA",
    state: "PA",
    city: "Philadelphia",
    type: "Private University",
    tuitionInState: 63452,
    tuitionOutState: 63452,
    tuition: "$63,452",
    acceptanceRate: "6%",
    acceptanceRateNum: 0.06,
    minGPA: 3.7,
    avgGPA: 3.95,
    ranking: 6,
    enrollmentSize: 22000,
    majors: ["Business", "Finance", "Economics", "Nursing", "Engineering", "Computer Science", "Biology", "Political Science"],
    tags: ["ivy-league", "research", "urban", "business", "elite", "diverse"],
    satRange: "1480-1560",
    actRange: "34-35",
    financialAidPercent: 52,
    avgAidAmount: 58000,
    graduationRate: 96,
    description: "An Ivy League university with the world's first business school (Wharton) and top nursing program.",
    website: "https://www.upenn.edu",
    region: "Northeast"
  },
  {
    id: "ccp",
    name: "Community College of Philadelphia",
    location: "Philadelphia, PA",
    state: "PA",
    city: "Philadelphia",
    type: "Community College",
    tuitionInState: 5790,
    tuitionOutState: 11580,
    tuition: "$5,790 (in-state) / $11,580 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.1,
    ranking: 10,
    enrollmentSize: 28000,
    majors: ["Nursing", "Business", "Liberal Arts", "Computer Science", "Criminal Justice", "Dental Hygiene", "Culinary"],
    tags: ["community", "affordable", "open-enrollment", "urban", "diverse", "vocational"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 85,
    avgAidAmount: 5000,
    graduationRate: 12,
    description: "Philadelphia's community college offering affordable education and strong workforce development programs.",
    website: "https://www.ccp.edu",
    region: "Northeast"
  },
  // ============ WASHINGTON ============
  {
    id: "uw",
    name: "University of Washington",
    location: "Seattle, WA",
    state: "WA",
    city: "Seattle",
    type: "Public University",
    tuitionInState: 12076,
    tuitionOutState: 40740,
    tuition: "$12,076 (in-state) / $40,740 (out-of-state)",
    acceptanceRate: "48%",
    acceptanceRateNum: 0.48,
    minGPA: 2.8,
    avgGPA: 3.7,
    ranking: 40,
    enrollmentSize: 48000,
    majors: ["Computer Science", "Engineering", "Business", "Biology", "Psychology", "Public Health", "Nursing", "Information Science"],
    tags: ["research", "stem", "tech-hub", "urban", "diverse", "innovation"],
    satRange: "1240-1460",
    actRange: "28-33",
    financialAidPercent: 50,
    avgAidAmount: 18000,
    graduationRate: 84,
    description: "A leading research university in the tech capital of the Pacific Northwest.",
    website: "https://www.washington.edu",
    region: "West"
  },
  // ============ ARIZONA ============
  {
    id: "asu",
    name: "Arizona State University",
    location: "Tempe, AZ",
    state: "AZ",
    city: "Tempe",
    type: "Public University",
    tuitionInState: 12044,
    tuitionOutState: 30592,
    tuition: "$12,044 (in-state) / $30,592 (out-of-state)",
    acceptanceRate: "88%",
    acceptanceRateNum: 0.88,
    minGPA: 2.0,
    avgGPA: 3.3,
    ranking: 105,
    enrollmentSize: 77000,
    majors: ["Business", "Engineering", "Computer Science", "Nursing", "Psychology", "Supply Chain", "Criminal Justice", "Education"],
    tags: ["large", "online-friendly", "innovative", "diverse", "affordable", "athletics"],
    satRange: "1060-1300",
    actRange: "21-28",
    financialAidPercent: 65,
    avgAidAmount: 12000,
    graduationRate: 68,
    description: "The largest public university in the US, ranked #1 in innovation for multiple consecutive years.",
    website: "https://www.asu.edu",
    region: "West"
  },
  // ============ VIRGINIA ============
  {
    id: "uva",
    name: "University of Virginia",
    location: "Charlottesville, VA",
    state: "VA",
    city: "Charlottesville",
    type: "Public University",
    tuitionInState: 19814,
    tuitionOutState: 55914,
    tuition: "$19,814 (in-state) / $55,914 (out-of-state)",
    acceptanceRate: "19%",
    acceptanceRateNum: 0.19,
    minGPA: 3.3,
    avgGPA: 4.3,
    ranking: 24,
    enrollmentSize: 26000,
    majors: ["Economics", "Business", "Biology", "Computer Science", "Engineering", "Government", "Psychology", "History"],
    tags: ["research", "prestigious", "athletics", "suburban", "historic"],
    satRange: "1350-1510",
    actRange: "31-35",
    financialAidPercent: 42,
    avgAidAmount: 26000,
    graduationRate: 94,
    description: "Thomas Jefferson's university, consistently ranked among the best public schools in the nation.",
    website: "https://www.virginia.edu",
    region: "South"
  },
  {
    id: "howard",
    name: "Howard University",
    location: "Washington, DC",
    state: "DC",
    city: "Washington",
    type: "Private University",
    tuitionInState: 30786,
    tuitionOutState: 30786,
    tuition: "$30,786",
    acceptanceRate: "36%",
    acceptanceRateNum: 0.36,
    minGPA: 2.8,
    avgGPA: 3.5,
    ranking: 80,
    enrollmentSize: 12000,
    majors: ["Biology", "Nursing", "Communications", "Political Science", "Business", "Computer Science", "Psychology", "Film"],
    tags: ["research", "diverse", "urban", "leadership", "arts"],
    satRange: "1090-1280",
    actRange: "22-28",
    financialAidPercent: 85,
    avgAidAmount: 16000,
    graduationRate: 65,
    description: "A top research university producing leaders in every field from politics to entertainment.",
    website: "https://www.howard.edu",
    region: "South"
  },
  // ============ COLORADO ============
  {
    id: "cu-boulder",
    name: "University of Colorado Boulder",
    location: "Boulder, CO",
    state: "CO",
    city: "Boulder",
    type: "Public University",
    tuitionInState: 13590,
    tuitionOutState: 40488,
    tuition: "$13,590 (in-state) / $40,488 (out-of-state)",
    acceptanceRate: "80%",
    acceptanceRateNum: 0.80,
    minGPA: 2.5,
    avgGPA: 3.5,
    ranking: 89,
    enrollmentSize: 38000,
    majors: ["Aerospace Engineering", "Business", "Computer Science", "Environmental Science", "Psychology", "Physics", "Biology"],
    tags: ["research", "outdoors", "stem", "athletics", "scenic", "innovation"],
    satRange: "1150-1360",
    actRange: "25-31",
    financialAidPercent: 45,
    avgAidAmount: 13000,
    graduationRate: 73,
    description: "A top research university nestled at the foot of the Rocky Mountains with strong STEM programs.",
    website: "https://www.colorado.edu",
    region: "West"
  },
  // ============ MINNESOTA ============
  {
    id: "umn",
    name: "University of Minnesota, Twin Cities",
    location: "Minneapolis, MN",
    state: "MN",
    city: "Minneapolis",
    type: "Public University",
    tuitionInState: 15466,
    tuitionOutState: 35238,
    tuition: "$15,466 (in-state) / $35,238 (out-of-state)",
    acceptanceRate: "73%",
    acceptanceRateNum: 0.73,
    minGPA: 2.5,
    avgGPA: 3.5,
    ranking: 53,
    enrollmentSize: 52000,
    majors: ["Engineering", "Computer Science", "Business", "Psychology", "Biology", "Nursing", "Economics", "Education"],
    tags: ["research", "large", "diverse", "urban", "stem", "affordable"],
    satRange: "1200-1420",
    actRange: "26-32",
    financialAidPercent: 58,
    avgAidAmount: 14000,
    graduationRate: 82,
    description: "A top-50 public university with strong engineering and health science programs in the Twin Cities.",
    website: "https://twin-cities.umn.edu",
    region: "Midwest"
  },
  // ============ TENNESSEE ============
  {
    id: "vanderbilt",
    name: "Vanderbilt University",
    location: "Nashville, TN",
    state: "TN",
    city: "Nashville",
    type: "Private University",
    tuitionInState: 62096,
    tuitionOutState: 62096,
    tuition: "$62,096",
    acceptanceRate: "6%",
    acceptanceRateNum: 0.06,
    minGPA: 3.7,
    avgGPA: 3.9,
    ranking: 18,
    enrollmentSize: 14000,
    majors: ["Economics", "Engineering", "Medicine", "Education", "Computer Science", "Neuroscience", "Music", "Political Science"],
    tags: ["elite", "research", "urban", "diverse", "small", "music-city"],
    satRange: "1460-1560",
    actRange: "33-35",
    financialAidPercent: 65,
    avgAidAmount: 55000,
    graduationRate: 94,
    description: "A top private research university in Music City with generous financial aid and strong academics.",
    website: "https://www.vanderbilt.edu",
    region: "South"
  },
  // ============ OREGON ============
  {
    id: "pcc",
    name: "Portland Community College",
    location: "Portland, OR",
    state: "OR",
    city: "Portland",
    type: "Community College",
    tuitionInState: 4680,
    tuitionOutState: 10300,
    tuition: "$4,680 (in-state) / $10,300 (out-of-state)",
    acceptanceRate: "Open Enrollment",
    acceptanceRateNum: 1.0,
    minGPA: 0.0,
    avgGPA: 2.3,
    ranking: 4,
    enrollmentSize: 50000,
    majors: ["Nursing", "Business", "Computer Science", "Welding", "Dental Hygiene", "Liberal Arts", "Automotive", "HVAC"],
    tags: ["community", "affordable", "open-enrollment", "urban", "vocational", "diverse"],
    satRange: "N/A",
    actRange: "N/A",
    financialAidPercent: 70,
    avgAidAmount: 5000,
    graduationRate: 20,
    description: "Oregon's largest post-secondary institution offering strong career-technical and transfer programs.",
    website: "https://www.pcc.edu",
    region: "West"
  },
  // ============ INDIANA ============
  {
    id: "purdue",
    name: "Purdue University",
    location: "West Lafayette, IN",
    state: "IN",
    city: "West Lafayette",
    type: "Public University",
    tuitionInState: 9992,
    tuitionOutState: 28794,
    tuition: "$9,992 (in-state) / $28,794 (out-of-state)",
    acceptanceRate: "53%",
    acceptanceRateNum: 0.53,
    minGPA: 2.5,
    avgGPA: 3.6,
    ranking: 43,
    enrollmentSize: 50000,
    majors: ["Engineering", "Computer Science", "Business", "Agriculture", "Pharmacy", "Aviation", "Biology", "Mathematics"],
    tags: ["research", "stem", "engineering-top", "affordable", "rural", "athletics"],
    satRange: "1180-1430",
    actRange: "26-33",
    financialAidPercent: 50,
    avgAidAmount: 13000,
    graduationRate: 82,
    description: "A world-class engineering and STEM university that has produced 28 astronauts.",
    website: "https://www.purdue.edu",
    region: "Midwest"
  },
  // ============ MARYLAND ============
  {
    id: "umd",
    name: "University of Maryland, College Park",
    location: "College Park, MD",
    state: "MD",
    city: "College Park",
    type: "Public University",
    tuitionInState: 11233,
    tuitionOutState: 39920,
    tuition: "$11,233 (in-state) / $39,920 (out-of-state)",
    acceptanceRate: "45%",
    acceptanceRateNum: 0.45,
    minGPA: 2.8,
    avgGPA: 4.3,
    ranking: 46,
    enrollmentSize: 41000,
    majors: ["Computer Science", "Business", "Engineering", "Biology", "Criminal Justice", "Journalism", "Government", "Economics"],
    tags: ["research", "stem", "large", "diverse", "athletics", "dc-area"],
    satRange: "1310-1480",
    actRange: "30-34",
    financialAidPercent: 48,
    avgAidAmount: 12000,
    graduationRate: 87,
    description: "Maryland's flagship university near Washington DC with strong CS, business, and engineering programs.",
    website: "https://www.umd.edu",
    region: "South"
  },
  // ============ LOUISIANA ============
  {
    id: "southern",
    name: "Southern University and A&M College",
    location: "Baton Rouge, LA",
    state: "LA",
    city: "Baton Rouge",
    type: "Public University",
    tuitionInState: 8878,
    tuitionOutState: 19936,
    tuition: "$8,878 (in-state) / $19,936 (out-of-state)",
    acceptanceRate: "52%",
    acceptanceRateNum: 0.52,
    minGPA: 2.0,
    avgGPA: 2.9,
    ranking: 120,
    enrollmentSize: 7000,
    majors: ["Nursing", "Criminal Justice", "Business", "Engineering", "Biology", "Computer Science", "Education", "Social Work"],
    tags: ["affordable", "diverse", "mid-range", "leadership", "athletics"],
    satRange: "910-1090",
    actRange: "17-22",
    financialAidPercent: 90,
    avgAidAmount: 9000,
    graduationRate: 33,
    description: "A major university system offering affordable education and strong community connections in Louisiana.",
    website: "https://www.subr.edu",
    region: "South"
  },
  // ============ WISCONSIN ============
  {
    id: "uw-madison",
    name: "University of Wisconsin-Madison",
    location: "Madison, WI",
    state: "WI",
    city: "Madison",
    type: "Public University",
    tuitionInState: 10796,
    tuitionOutState: 39427,
    tuition: "$10,796 (in-state) / $39,427 (out-of-state)",
    acceptanceRate: "49%",
    acceptanceRateNum: 0.49,
    minGPA: 2.8,
    avgGPA: 3.8,
    ranking: 35,
    enrollmentSize: 47000,
    majors: ["Computer Science", "Business", "Engineering", "Biology", "Economics", "Political Science", "Psychology", "Data Science"],
    tags: ["research", "large", "athletics", "stem", "diverse", "scenic"],
    satRange: "1280-1470",
    actRange: "28-33",
    financialAidPercent: 50,
    avgAidAmount: 15000,
    graduationRate: 88,
    description: "A Big Ten powerhouse with top research programs in computing, engineering, and life sciences.",
    website: "https://www.wisc.edu",
    region: "Midwest"
  }
];

// Helper function to format tuition for display
export function formatTuition(amount: number): string {
  return `$${amount.toLocaleString()}`;
}

// Get unique states from database
export function getStates(): string[] {
  return [...new Set(collegeDatabase.map(c => c.state))].sort();
}

// Get unique types
export function getCollegeTypes(): string[] {
  return [...new Set(collegeDatabase.map(c => c.type))].sort();
}

// Get all unique majors
export function getAllMajors(): string[] {
  const majors = new Set<string>();
  for (const college of collegeDatabase) {
    for (const major of college.majors) {
      majors.add(major);
    }
  }
  return [...majors].sort();
}
